@baseUrl = http://localhost:3333

POST {{baseUrl}}/registers
Content-Type: application/json

{
  "name": "Cristiano Rolnado",
  "username": "ronaldo",
  "password": "123mudar"
}

###

POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "username": "ronaldo",
  "password": "123mudar"
}