@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name register-users
POST {{baseUrl}}/registers
Content-Type: application/json

{
  "name": "Cristiano Rolnado",
  "username": "ronaldo",
  "password": "123mudar"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "username": "ronaldo",
  "password": "123mudar"
}


###

# @name create-tasks
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Planejamento de Marketing",
  "description": "Criar um plano de marketing para o próximo trimestre",
  "startAt": "2024-07-17T11:00:00",
  "endAt": "2024-07-25T12:15:00",
  "priority": "Alta"

}

###

# @name fetch-tasks
GET {{baseUrl}}/tasks
Authorization: Bearer {{authToken}}

###

# @name fetch-one-task
GET {{baseUrl}}/tasks/448d59fb-7ef1-45cc-be76-81426febcbe7
Authorization: Bearer {{authToken}}